using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EndGame : MonoBehaviour
{
    [SerializeField] private int puntuacionNecesaria; // Puntuaci贸n requerida para finalizar el juego
    [SerializeField] private Score score; // Sistema de puntuaci贸n
    [SerializeField] private AudioClip audioClip;

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Player"))
        {
            // Verificar si la puntuaci贸n es suficiente
            if (score.GetPuntos() >= puntuacionNecesaria)
            {
                AudioSource.PlayClipAtPoint(audioClip, transform.position);
                Finalizar(); // Finalizar el juego
            }
            else
            {
                Debug.Log("No tienes suficiente puntuaci贸n para ganar.");
            }
        }
    }

    private void Finalizar()
    {
        Time.timeScale = 0f;
    }
}
